"""Prompt builders for changelog generation and self-evaluation."""

from __future__ import annotations

from changelog.classifier import ClassifiedChanges

SYSTEM_PROMPT = (
    "You are an expert technical writer specialising in software release notes and changelogs.\n"
    "Your task is to generate clear, accurate, and well-structured changelogs "
    "for software releases.\n"
    "Write for a technical audience: developers who need to understand what changed and whether "
    "they need to take action.\n"
    "Be concise but complete. Never invent changes that are not in the provided data."
)


def get_system_prompt() -> str:
    """Return the system prompt shared by generation and evaluation calls."""
    return SYSTEM_PROMPT


def build_generation_prompt(
    *,
    classified: ClassifiedChanges,
    release_tag: str,
    release_name: str,
    previous_tag: str | None,
    language: str,
    repo: str,
    feedback: str = "",
    missing: list[str] | None = None,
) -> str:
    """Build the user prompt for changelog generation."""
    if previous_tag:
        context = f"This release covers changes since {previous_tag}."
    else:
        context = "This is the first release."

    sections = _build_change_sections(classified)

    prompt = (
        f"Generate a changelog for release {release_tag} of {repo}.\n"
        f"{context}\n\n"
        f"Write the changelog in {language}.\n\n"
        f"## Changes to document\n\n{sections}\n"
        f"## Output format\n\n"
        f"Produce ONLY the changelog body in Markdown. Do not include a preamble or conclusion.\n"
        f"Use the following structure:\n\n"
        f"## What's Changed in {release_tag}\n\n"
        f"> {{one-sentence summary of the most important change in this release}}\n\n"
        f"{{If breaking changes exist, open with:}}\n"
        f"### ⚠️ Breaking Changes\n"
        f"- {{description}}\n\n"
        f"### ✨ New Features\n"
        f"- {{description}}\n\n"
        f"### 🐛 Bug Fixes\n"
        f"- {{description}}\n\n"
        f"### 🚀 Performance\n"
        f"- {{description}}  [omit section if empty]\n\n"
        f"### 📚 Documentation\n"
        f"- {{description}}  [omit section if empty]\n\n"
        f"### 🔧 Maintenance\n"
        f"- {{description combining refactor + chore + other, omit if empty}}\n\n"
        f"---\n"
        f"*Generated by [ai-changelog-generator]"
        f"(https://github.com/AndreaBonn/ai-changelog-generator)*\n\n"
        f"Rules:\n"
        f"- Omit sections that have no items.\n"
        f"- Keep each bullet to one line.\n"
        f'- If a PR number is available, include it as "(#N)" at the end of the line.\n'
        f"- Do not fabricate changes.\n"
        f"- The summary sentence must reflect the actual content.\n"
    )

    if feedback:
        prompt += f"- Previous evaluation feedback to address: {feedback}\n"
    if missing:
        prompt += f"- Missing items to include: {', '.join(missing)}\n"

    return prompt


def build_evaluation_prompt(
    *,
    changelog_body: str,
    classified: ClassifiedChanges,
    language: str,
) -> str:
    """Build the user prompt for self-evaluation of a generated changelog."""
    sections = _build_change_sections(classified)

    return (
        f"You are reviewing a generated changelog for correctness and completeness.\n\n"
        f"## Generated changelog\n{changelog_body}\n\n"
        f"## Source data (ground truth)\n\n{sections}\n"
        f"## Your task\n\n"
        f"Check whether the changelog:\n"
        f"1. Includes ALL breaking changes — this is mandatory\n"
        f"2. Includes all significant features and bug fixes\n"
        f"3. Does not contain invented or hallucinated items not present in the source data\n"
        f"4. Has the correct overall tone and language ({language})\n\n"
        f"Respond ONLY with valid JSON, no markdown fences, no explanation:\n"
        f"{{\n"
        f'  "ok": true/false,\n'
        f'  "feedback": "brief description of issues found, or empty string if ok",\n'
        f'  "missing": ["item 1 that was missing", "item 2 that was missing"]\n'
        f"}}\n\n"
        f'Set "ok" to true if the changelog is acceptable. Set to false only if:\n'
        f"- A breaking change is missing, OR\n"
        f"- More than 2 significant features or fixes are missing, OR\n"
        f"- There are clearly hallucinated items\n\n"
        f"Do not be overly strict. Minor omissions of chores or refactoring are acceptable.\n"
    )


def _build_change_sections(classified: ClassifiedChanges) -> str:
    """Format classified changes into labeled sections for the prompt."""
    parts: list[str] = []

    _add_section(parts, "Breaking changes", classified.breaking)
    _add_section(parts, "New features", classified.features)
    _add_section(parts, "Bug fixes", classified.fixes)
    _add_section(parts, "Performance improvements", classified.performance)
    _add_section(parts, "Documentation", classified.docs)
    _add_section(parts, "Refactoring", classified.refactor)
    _add_section(parts, "Chores and maintenance", classified.chore)
    _add_section(parts, "Other changes", classified.other)

    return "\n".join(parts)


def _add_section(parts: list[str], title: str, items: list[str]) -> None:
    """Add a section to the prompt parts, showing (none) for empty lists."""
    header = f"### {title}\n"
    body = "\n".join(f"- {item}" for item in items) if items else "(none)"
    parts.append(f"{header}{body}\n")
